//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV2Reference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameInfoResponse", Namespace="http://www.serviceobjects.com")]
    public partial class NameInfoResponse : object
    {
        
        private NV2Reference.NameInfo NameInfoField;
        
        private NV2Reference.NV2Error ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NV2Reference.NameInfo NameInfo
        {
            get
            {
                return this.NameInfoField;
            }
            set
            {
                this.NameInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public NV2Reference.NV2Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameInfo", Namespace="http://www.serviceobjects.com")]
    public partial class NameInfo : object
    {
        
        private NV2Reference.NV2Name BestGuessNameField;
        
        private string PrefixField;
        
        private string FirstNameField;
        
        private string MiddleNameField;
        
        private string LastNameField;
        
        private string SuffixField;
        
        private bool FirstNameFoundField;
        
        private bool IsCommonFirstNameField;
        
        private string FirstNameOriginField;
        
        private bool LastNameFoundField;
        
        private bool IsCommonLastNameField;
        
        private string GenderField;
        
        private string FirstNameAltField;
        
        private string MiddleNameAltField;
        
        private string LastNameAltField;
        
        private bool FirstNameAltFoundField;
        
        private bool LastNameAltFoundField;
        
        private string GenderAltField;
        
        private string RelatedNamesField;
        
        private int VulgarityScoreField;
        
        private int CelebrityScoreField;
        
        private int BogusScoreField;
        
        private int GarbageScoreField;
        
        private int FirstNameDictionaryScoreField;
        
        private int MiddleNameDictionaryScoreField;
        
        private int LastNameDictionaryScoreField;
        
        private string IsNameGoodField;
        
        private string StatusCodesField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NV2Reference.NV2Name BestGuessName
        {
            get
            {
                return this.BestGuessNameField;
            }
            set
            {
                this.BestGuessNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefix
        {
            get
            {
                return this.PrefixField;
            }
            set
            {
                this.PrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Suffix
        {
            get
            {
                return this.SuffixField;
            }
            set
            {
                this.SuffixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool FirstNameFound
        {
            get
            {
                return this.FirstNameFoundField;
            }
            set
            {
                this.FirstNameFoundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool IsCommonFirstName
        {
            get
            {
                return this.IsCommonFirstNameField;
            }
            set
            {
                this.IsCommonFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string FirstNameOrigin
        {
            get
            {
                return this.FirstNameOriginField;
            }
            set
            {
                this.FirstNameOriginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool LastNameFound
        {
            get
            {
                return this.LastNameFoundField;
            }
            set
            {
                this.LastNameFoundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool IsCommonLastName
        {
            get
            {
                return this.IsCommonLastNameField;
            }
            set
            {
                this.IsCommonLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string FirstNameAlt
        {
            get
            {
                return this.FirstNameAltField;
            }
            set
            {
                this.FirstNameAltField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string MiddleNameAlt
        {
            get
            {
                return this.MiddleNameAltField;
            }
            set
            {
                this.MiddleNameAltField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string LastNameAlt
        {
            get
            {
                return this.LastNameAltField;
            }
            set
            {
                this.LastNameAltField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public bool FirstNameAltFound
        {
            get
            {
                return this.FirstNameAltFoundField;
            }
            set
            {
                this.FirstNameAltFoundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public bool LastNameAltFound
        {
            get
            {
                return this.LastNameAltFoundField;
            }
            set
            {
                this.LastNameAltFoundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string GenderAlt
        {
            get
            {
                return this.GenderAltField;
            }
            set
            {
                this.GenderAltField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string RelatedNames
        {
            get
            {
                return this.RelatedNamesField;
            }
            set
            {
                this.RelatedNamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public int VulgarityScore
        {
            get
            {
                return this.VulgarityScoreField;
            }
            set
            {
                this.VulgarityScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public int CelebrityScore
        {
            get
            {
                return this.CelebrityScoreField;
            }
            set
            {
                this.CelebrityScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public int BogusScore
        {
            get
            {
                return this.BogusScoreField;
            }
            set
            {
                this.BogusScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public int GarbageScore
        {
            get
            {
                return this.GarbageScoreField;
            }
            set
            {
                this.GarbageScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public int FirstNameDictionaryScore
        {
            get
            {
                return this.FirstNameDictionaryScoreField;
            }
            set
            {
                this.FirstNameDictionaryScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public int MiddleNameDictionaryScore
        {
            get
            {
                return this.MiddleNameDictionaryScoreField;
            }
            set
            {
                this.MiddleNameDictionaryScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public int LastNameDictionaryScore
        {
            get
            {
                return this.LastNameDictionaryScoreField;
            }
            set
            {
                this.LastNameDictionaryScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public string IsNameGood
        {
            get
            {
                return this.IsNameGoodField;
            }
            set
            {
                this.IsNameGoodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string StatusCodes
        {
            get
            {
                return this.StatusCodesField;
            }
            set
            {
                this.StatusCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NV2Error", Namespace="http://www.serviceobjects.com")]
    public partial class NV2Error : object
    {
        
        private string TypeField;
        
        private string TypeCodeField;
        
        private string DescField;
        
        private string DescCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeCode
        {
            get
            {
                return this.TypeCodeField;
            }
            set
            {
                this.TypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string DescCode
        {
            get
            {
                return this.DescCodeField;
            }
            set
            {
                this.DescCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NV2Name", Namespace="http://www.serviceobjects.com")]
    public partial class NV2Name : object
    {
        
        private string PrefixField;
        
        private string FirstNameField;
        
        private string MiddleNameField;
        
        private string LastNameField;
        
        private string SuffixField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefix
        {
            get
            {
                return this.PrefixField;
            }
            set
            {
                this.PrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Suffix
        {
            get
            {
                return this.SuffixField;
            }
            set
            {
                this.SuffixField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameInfoV2Response", Namespace="http://www.serviceobjects.com")]
    public partial class NameInfoV2Response : object
    {
        
        private NV2Reference.NameInfoV2 NameInfoV2Field;
        
        private NV2Reference.NV2Error ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public NV2Reference.NameInfoV2 NameInfoV2
        {
            get
            {
                return this.NameInfoV2Field;
            }
            set
            {
                this.NameInfoV2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public NV2Reference.NV2Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameInfoV2", Namespace="http://www.serviceobjects.com")]
    public partial class NameInfoV2 : object
    {
        
        private NV2Reference.NV2Name BestGuessNameField;
        
        private string NameInField;
        
        private string NameClassificationField;
        
        private string PrefixField;
        
        private string FirstNameField;
        
        private string MiddleNameField;
        
        private string LastNameField;
        
        private string SuffixField;
        
        private bool FirstNameFoundField;
        
        private bool IsCommonFirstNameField;
        
        private string FirstNameOriginField;
        
        private string FirstNameSimilarField;
        
        private bool LastNameFoundField;
        
        private bool IsCommonLastNameField;
        
        private string LastNameOriginField;
        
        private string LastNameSimilarField;
        
        private string GenderField;
        
        private string FirstNameAltField;
        
        private string MiddleNameAltField;
        
        private string LastNameAltField;
        
        private bool FirstNameAltFoundField;
        
        private bool LastNameAltFoundField;
        
        private string GenderAltField;
        
        private string RelatedNamesField;
        
        private bool IsCorrectedNameField;
        
        private bool IsBusinessNameField;
        
        private string BusinessNameField;
        
        private int VulgarityScoreField;
        
        private int CelebrityScoreField;
        
        private int BogusScoreField;
        
        private int GarbageScoreField;
        
        private int FirstNameDictionaryScoreField;
        
        private int MiddleNameDictionaryScoreField;
        
        private int LastNameDictionaryScoreField;
        
        private int OverallNameScoreField;
        
        private string IsNameGoodField;
        
        private string StatusCodesField;
        
        private string StatusField;
        
        private string FirstNameLanguageField;
        
        private string MiddleNameLanguageField;
        
        private string LastNameLanguageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NV2Reference.NV2Name BestGuessName
        {
            get
            {
                return this.BestGuessNameField;
            }
            set
            {
                this.BestGuessNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameIn
        {
            get
            {
                return this.NameInField;
            }
            set
            {
                this.NameInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string NameClassification
        {
            get
            {
                return this.NameClassificationField;
            }
            set
            {
                this.NameClassificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Prefix
        {
            get
            {
                return this.PrefixField;
            }
            set
            {
                this.PrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Suffix
        {
            get
            {
                return this.SuffixField;
            }
            set
            {
                this.SuffixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool FirstNameFound
        {
            get
            {
                return this.FirstNameFoundField;
            }
            set
            {
                this.FirstNameFoundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool IsCommonFirstName
        {
            get
            {
                return this.IsCommonFirstNameField;
            }
            set
            {
                this.IsCommonFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string FirstNameOrigin
        {
            get
            {
                return this.FirstNameOriginField;
            }
            set
            {
                this.FirstNameOriginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string FirstNameSimilar
        {
            get
            {
                return this.FirstNameSimilarField;
            }
            set
            {
                this.FirstNameSimilarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public bool LastNameFound
        {
            get
            {
                return this.LastNameFoundField;
            }
            set
            {
                this.LastNameFoundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool IsCommonLastName
        {
            get
            {
                return this.IsCommonLastNameField;
            }
            set
            {
                this.IsCommonLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string LastNameOrigin
        {
            get
            {
                return this.LastNameOriginField;
            }
            set
            {
                this.LastNameOriginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string LastNameSimilar
        {
            get
            {
                return this.LastNameSimilarField;
            }
            set
            {
                this.LastNameSimilarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string FirstNameAlt
        {
            get
            {
                return this.FirstNameAltField;
            }
            set
            {
                this.FirstNameAltField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string MiddleNameAlt
        {
            get
            {
                return this.MiddleNameAltField;
            }
            set
            {
                this.MiddleNameAltField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string LastNameAlt
        {
            get
            {
                return this.LastNameAltField;
            }
            set
            {
                this.LastNameAltField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public bool FirstNameAltFound
        {
            get
            {
                return this.FirstNameAltFoundField;
            }
            set
            {
                this.FirstNameAltFoundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public bool LastNameAltFound
        {
            get
            {
                return this.LastNameAltFoundField;
            }
            set
            {
                this.LastNameAltFoundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public string GenderAlt
        {
            get
            {
                return this.GenderAltField;
            }
            set
            {
                this.GenderAltField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public string RelatedNames
        {
            get
            {
                return this.RelatedNamesField;
            }
            set
            {
                this.RelatedNamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public bool IsCorrectedName
        {
            get
            {
                return this.IsCorrectedNameField;
            }
            set
            {
                this.IsCorrectedNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public bool IsBusinessName
        {
            get
            {
                return this.IsBusinessNameField;
            }
            set
            {
                this.IsBusinessNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public string BusinessName
        {
            get
            {
                return this.BusinessNameField;
            }
            set
            {
                this.BusinessNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public int VulgarityScore
        {
            get
            {
                return this.VulgarityScoreField;
            }
            set
            {
                this.VulgarityScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public int CelebrityScore
        {
            get
            {
                return this.CelebrityScoreField;
            }
            set
            {
                this.CelebrityScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public int BogusScore
        {
            get
            {
                return this.BogusScoreField;
            }
            set
            {
                this.BogusScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public int GarbageScore
        {
            get
            {
                return this.GarbageScoreField;
            }
            set
            {
                this.GarbageScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public int FirstNameDictionaryScore
        {
            get
            {
                return this.FirstNameDictionaryScoreField;
            }
            set
            {
                this.FirstNameDictionaryScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=32)]
        public int MiddleNameDictionaryScore
        {
            get
            {
                return this.MiddleNameDictionaryScoreField;
            }
            set
            {
                this.MiddleNameDictionaryScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=33)]
        public int LastNameDictionaryScore
        {
            get
            {
                return this.LastNameDictionaryScoreField;
            }
            set
            {
                this.LastNameDictionaryScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=34)]
        public int OverallNameScore
        {
            get
            {
                return this.OverallNameScoreField;
            }
            set
            {
                this.OverallNameScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=35)]
        public string IsNameGood
        {
            get
            {
                return this.IsNameGoodField;
            }
            set
            {
                this.IsNameGoodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=36)]
        public string StatusCodes
        {
            get
            {
                return this.StatusCodesField;
            }
            set
            {
                this.StatusCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=37)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=38)]
        public string FirstNameLanguage
        {
            get
            {
                return this.FirstNameLanguageField;
            }
            set
            {
                this.FirstNameLanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=39)]
        public string MiddleNameLanguage
        {
            get
            {
                return this.MiddleNameLanguageField;
            }
            set
            {
                this.MiddleNameLanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=40)]
        public string LastNameLanguage
        {
            get
            {
                return this.LastNameLanguageField;
            }
            set
            {
                this.LastNameLanguageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.serviceobjects.com", ConfigurationName="NV2Reference.INV2Library")]
    public interface INV2Library
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/INV2Library/ValidateName_GETXML", ReplyAction="http://www.serviceobjects.com/INV2Library/ValidateName_GETXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="NameInfoResponse")]
        System.Threading.Tasks.Task<NV2Reference.NameInfoResponse> ValidateName_GETXMLAsync(string Name, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/INV2Library/ValidateName_QUERYGETXML", ReplyAction="http://www.serviceobjects.com/INV2Library/ValidateName_QUERYGETXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="NameInfoResponse")]
        System.Threading.Tasks.Task<NV2Reference.NameInfoResponse> ValidateName_QUERYGETXMLAsync(string Name, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/INV2Library/ValidateName_GETJSON", ReplyAction="http://www.serviceobjects.com/INV2Library/ValidateName_GETJSONResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="NameInfoResponse")]
        System.Threading.Tasks.Task<NV2Reference.NameInfoResponse> ValidateName_GETJSONAsync(string Name, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/INV2Library/ValidateName_POST", ReplyAction="http://www.serviceobjects.com/INV2Library/ValidateName_POSTResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="NameInfoResponse")]
        System.Threading.Tasks.Task<NV2Reference.NameInfoResponse> ValidateName_POSTAsync(string Name, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/INV2Library/ValidateName_PUT", ReplyAction="http://www.serviceobjects.com/INV2Library/ValidateName_PUTResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="NameInfoResponse")]
        System.Threading.Tasks.Task<NV2Reference.NameInfoResponse> ValidateName_PUTAsync(string Name, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/INV2Library/ValidateName", ReplyAction="http://www.serviceobjects.com/INV2Library/ValidateNameResponse")]
        System.Threading.Tasks.Task<NV2Reference.NameInfoResponse> ValidateNameAsync(string Name, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/INV2Library/ValidateNameV2_GETXML", ReplyAction="http://www.serviceobjects.com/INV2Library/ValidateNameV2_GETXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="NameInfoV2Response")]
        System.Threading.Tasks.Task<NV2Reference.NameInfoV2Response> ValidateNameV2_GETXMLAsync(string Name, string Option, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/INV2Library/ValidateNameV2_QUERYGETXML", ReplyAction="http://www.serviceobjects.com/INV2Library/ValidateNameV2_QUERYGETXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="NameInfoV2Response")]
        System.Threading.Tasks.Task<NV2Reference.NameInfoV2Response> ValidateNameV2_QUERYGETXMLAsync(string Name, string Option, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/INV2Library/ValidateNameV2_GETJSON", ReplyAction="http://www.serviceobjects.com/INV2Library/ValidateNameV2_GETJSONResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="NameInfoV2Response")]
        System.Threading.Tasks.Task<NV2Reference.NameInfoV2Response> ValidateNameV2_GETJSONAsync(string Name, string Option, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/INV2Library/ValidateNameV2_POSTJSON", ReplyAction="http://www.serviceobjects.com/INV2Library/ValidateNameV2_POSTJSONResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="NameInfoV2Response")]
        System.Threading.Tasks.Task<NV2Reference.NameInfoV2Response> ValidateNameV2_POSTJSONAsync(string Name, string Option, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/INV2Library/ValidateNameV2_POSTXML", ReplyAction="http://www.serviceobjects.com/INV2Library/ValidateNameV2_POSTXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="NameInfoV2Response")]
        System.Threading.Tasks.Task<NV2Reference.NameInfoV2Response> ValidateNameV2_POSTXMLAsync(string Name, string Option, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/INV2Library/ValidateNameV2", ReplyAction="http://www.serviceobjects.com/INV2Library/ValidateNameV2Response")]
        System.Threading.Tasks.Task<NV2Reference.NameInfoV2Response> ValidateNameV2Async(string Name, string Option, string LicenseKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface INV2LibraryChannel : NV2Reference.INV2Library, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class NV2LibraryClient : System.ServiceModel.ClientBase<NV2Reference.INV2Library>, NV2Reference.INV2Library
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NV2LibraryClient() : 
                base(NV2LibraryClient.GetDefaultBinding(), NV2LibraryClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NV2LibraryClient(EndpointConfiguration endpointConfiguration) : 
                base(NV2LibraryClient.GetBindingForEndpoint(endpointConfiguration), NV2LibraryClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NV2LibraryClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NV2LibraryClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NV2LibraryClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NV2LibraryClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NV2LibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NV2Reference.NameInfoResponse> ValidateName_GETXMLAsync(string Name, string LicenseKey)
        {
            return base.Channel.ValidateName_GETXMLAsync(Name, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<NV2Reference.NameInfoResponse> ValidateName_QUERYGETXMLAsync(string Name, string LicenseKey)
        {
            return base.Channel.ValidateName_QUERYGETXMLAsync(Name, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<NV2Reference.NameInfoResponse> ValidateName_GETJSONAsync(string Name, string LicenseKey)
        {
            return base.Channel.ValidateName_GETJSONAsync(Name, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<NV2Reference.NameInfoResponse> ValidateName_POSTAsync(string Name, string LicenseKey)
        {
            return base.Channel.ValidateName_POSTAsync(Name, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<NV2Reference.NameInfoResponse> ValidateName_PUTAsync(string Name, string LicenseKey)
        {
            return base.Channel.ValidateName_PUTAsync(Name, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<NV2Reference.NameInfoResponse> ValidateNameAsync(string Name, string LicenseKey)
        {
            return base.Channel.ValidateNameAsync(Name, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<NV2Reference.NameInfoV2Response> ValidateNameV2_GETXMLAsync(string Name, string Option, string LicenseKey)
        {
            return base.Channel.ValidateNameV2_GETXMLAsync(Name, Option, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<NV2Reference.NameInfoV2Response> ValidateNameV2_QUERYGETXMLAsync(string Name, string Option, string LicenseKey)
        {
            return base.Channel.ValidateNameV2_QUERYGETXMLAsync(Name, Option, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<NV2Reference.NameInfoV2Response> ValidateNameV2_GETJSONAsync(string Name, string Option, string LicenseKey)
        {
            return base.Channel.ValidateNameV2_GETJSONAsync(Name, Option, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<NV2Reference.NameInfoV2Response> ValidateNameV2_POSTJSONAsync(string Name, string Option, string LicenseKey)
        {
            return base.Channel.ValidateNameV2_POSTJSONAsync(Name, Option, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<NV2Reference.NameInfoV2Response> ValidateNameV2_POSTXMLAsync(string Name, string Option, string LicenseKey)
        {
            return base.Channel.ValidateNameV2_POSTXMLAsync(Name, Option, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<NV2Reference.NameInfoV2Response> ValidateNameV2Async(string Name, string Option, string LicenseKey)
        {
            return base.Channel.ValidateNameV2Async(Name, Option, LicenseKey);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.soap))
            {
                return new System.ServiceModel.EndpointAddress("https://sws.serviceobjects.com/NV2/api.svc/soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NV2LibraryClient.GetBindingForEndpoint(EndpointConfiguration.soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NV2LibraryClient.GetEndpointAddress(EndpointConfiguration.soap);
        }
        
        public enum EndpointConfiguration
        {
            
            soap,
        }
    }
}
